<?php

namespace App\FMS\Site\ValueObjects;

class QuoteNumber {
    const QUOTE_PREFIX_CRONULLA_RETAIL = 'Q';
    const QUOTE_PREFIX_CRONULLA_COMMERCIAL = '';
    const QUOTE_PREFIX_KOGRAH_CARPET = 'QN';
    const QUOTE_PREFIX_SHIRE_CARPET = 'QN';

    const QUOTE_NUMBER_FROM_CRONULLA_RETAIL = 100000;
    const QUOTE_NUMBER_FROM_CRONULLA_COMMERCIAL = 40000;
    const QUOTE_NUMBER_FROM_KOGRAH_CARPET = 300000;
    const QUOTE_NUMBER_FROM_SHIRE_CARPET = 200000;

    const QUOTE_NUMBER_TO_CRONULLA_RETAIL = 199999;
    const QUOTE_NUMBER_TO_CRONULLA_COMMERCIAL = 99999;
    const QUOTE_NUMBER_TO_KOGRAH_CARPET = 399999;
    const QUOTE_NUMBER_TO_SHIRE_CARPET = 299999;
}
